### PR TITLE
Create CITATION.bib

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by juliohm** [comment]
Hi @asinghvi17 , thank you for the PR. Is there any part of the Julia ecosystem that is going to use this CITATION.bib file?

**Comment by asinghvi17** [comment]
Eventually there will be a package which gives you a citation file based on your Project.toml, but now it's just a matter of convenience.

**Comment by juliohm** [comment]
Do you have anything in mind that uses this CITATION.bib file currently? I would rather wait for the support in Project.toml directly, the BIBTeX entry is already in the README.md, wouldn't it be sufficient for now?

**Comment by asinghvi17** [comment]
CITATION.bib will remain a separate file, but the tool will look at some arbitrary project's dependencies, find their CITATION.bibs, and then create a unified file.  That was the idea behind the standard, anyway...

**Comment by juliohm** [comment]
Got it. That makes sense. I will push a small change to the file (regarding the entry name), and merge. Thanks again for the PR :ok_hand:

**Comment by asinghvi17** [comment]
The entry name is supposed to be that way...from julialang.org/research:
> In order to make Julia packages and projects easy to cite, the community has settled on a standard location and format for bibliographic information. Please add a CITATION.bib file (BibTeX format) in the top-level directory of your package or repo. The key for the bib entry should be <PackageName.jl>-<year>-<letter> (Use a letter if you have multiple citations in same year). For example, see the CITATION.bib file in the Julia repo. We welcome additions to this list in the form of pull requests.

**Comment by juliohm** [comment]
Saw it too late, fixing it back. Thanks for the pointer!

**Pull request merged**
