### PR TITLE
Projects for doc building and code coverage

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by juliohm** [comment]
Thanks! I will wait the build to finish and then merge :100:

**Comment by juliohm** [comment]
So we need to also list `Random` and `Statistics` in the project file? I learned that they shouldn't appear in REQUIRE files for example.

**Comment by fredrikekre** [comment]
Yea, but they need to be in `Project.toml` files.

**Comment by juliohm** [comment]
I am still getting a build issue in the docs, could you please take a quick look? I don't know what is causing it: https://travis-ci.org/juliohm/GeoStats.jl/jobs/423764840#L624-L638

**Comment by fredrikekre** [comment]
What issue? Seems to have worked?

**Comment by juliohm** [comment]
There is an error mentioning that GeoStats.jl was not found. Later there are other issues saying that paths to generated images with Plots.jl are also not found?

**Comment by fredrikekre** [comment]
Oh, I scrolled down, where it looked like everything worked since
```
Documenter: New docs identical to the old -- not committing nor pushing.
```
I'll have a look.

**Pull request merged**
